# Site settings
title: Digital Ocean Droplet Preview
email: mattgraham@kickthebox.com
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "http://madebygraham.com/digitalocean-temp" # the base hostname & protocol for your site
twitter_username: michigangraham
github_username:  mattgraham

# Build settings
markdown: kramdown

kramdown:
  input: GFM

sass:
  sass_dir: /assets/sass
