# Site settings
title: Digital Ocean Droplet Preview
email: mattgraham@kickthebox.com
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://madebygraham.com/do" # the base hostname & protocol for your site
twitter_username: michigangraham
github_username:  mattgraham

# Build settings
markdown: kramdown

sass:
  sass_dir: /assets/_sass
